export default function Head() {
  return (
    <>
      <title>Educated App</title>
      <meta content='width=device-width, initial-scale=1.0, user-scalable=no' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/ICON.png' />
    </>
  )
}
